gradle

// 1. 这里只管插件，坚决不写下载地址（防止再起冲突）

buildscript {

dependencies {

classpath 'com.android.tools.build:gradle:7.4.2'

classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.22"

}

}

// 2. 这里也删光光，什么都不留

allprojects {

}

// 3. 【终极必杀技】直接把国内下载地址硬塞在这里！

// 不管机器读不读其他配置，这里它一定能看到，保证依赖包100%能下载下来

ext {

repo阿里云 = 'https://maven.aliyun.com/repository/public/
'

repo腾讯云 = 'https://mirrors.cloud.tencent.com/repository/maven-public/
'
