name: Build Debug APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    # 【新增关键行】：指定工作目录，告诉打包机去 SecondScreenMVP 文件夹里干活
    defaults:
      run:
        working-directory: SecondScreenMVP
        
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Grant execute permission
        run: chmod +x gradlew
        
      - name: Build with Gradle
        run: ./gradlew assembleDebug
